// Helper utilities for resource editor components

// Re-export from imageLoaders for backward compatibility
export { isSupportedImageFormat, getIconPath } from './imageLoaders';

// Option arrays for dropdown selects
export const effectTypes = [
  'DST_STR',
  'DST_DEX',
  'DST_INT',
  'DST_STA',
  'DST_YOY_DMG',
  'DST_BOW_DMG',
  'DST_CHR_RANGE',
  'DST_BLOCK_RANGE',
  'DST_CHR_CHANCECRITICAL',
  'DST_CHR_BLEEDING',
  'DST_SPEED',
  'DST_ABILITY_MIN',
  'DST_ABILITY_MAX',
  'DST_BLOCK_MELEE',
  'DST_MASTRY_EARTH',
  'DST_STOP_MOVEMENT',
  'DST_MASTRY_FIRE',
  'DST_MASTRY_WATER',
  'DST_MASTRY_ELECTRICITY',
  'DST_MASTRY_WIND',
  'DST_KNUCKLE_DMG',
  'DST_PVP_DMG_RATE',
  'DST_ATTACKSPEED',
  'DST_SWD_DMG',
  'DST_ADJDEF',
  'DST_RESIST_MAGIC',
  'DST_RESIST_ELECTRICITY',
  'DST_REFLECT_DAMAGE',
  'DST_RESIST_FIRE',
  'DST_RESIST_WIND',
  'DST_RESIST_WATER',
  'DST_RESIST_EARTH',
  'DST_AXE_DMG',
  'DST_HP_MAX',
  'DST_MP_MAX',
  'DST_FP_MAX',
  'DST_HP',
  'DST_MP',
  'DST_FP',
  'DST_HP_RECOVERY',
  'DST_MP_RECOVERY',
  'DST_FP_RECOVERY',
  'DST_KILL_HP',
  'DST_KILL_MP',
  'DST_KILL_FP',
  'DST_ADJ_HITRATE',
  'DST_CLEARBUFF',
  'DST_CHR_STEALHP_IMM',
  'DST_ATTACKSPEED_RATE',
  'DST_HP_MAX_RATE',
  'DST_MP_MAX_RATE',
  'DST_FP_MAX_RATE',
  'DST_CHR_WEAEATKCHANGE',
  'DST_CHR_STEALHP',
  'DST_CHR_CHANCESTUN',
  'DST_AUTOHP',
  'DST_CHR_CHANCEDARK',
  'DST_CHR_CHANCEPOISON',
  'DST_IMMUNITY',
  'DST_ADDMAGIC',
  'DST_CHR_DMG',
  'DST_CHRSTATE',
  'DST_PARRY',
  'DST_ATKPOWER_RATE',
  'DST_EXPERIENCE',
  'DST_JUMPING',
  'DST_CHR_CHANCESTEALHP',
  'DST_CHR_CHANCEBLEEDING',
  'DST_RECOVERY_EXP',
  'DST_ADJDEF_RATE',
  'DST_MP_DEC_RATE',
  'DST_FP_DEC_RATE',
  'DST_SPELL_RATE',
  'DST_CAST_CRITICAL_RATE',
  'DST_CRITICAL_BONUS',
  'DST_SKILL_LEVEL',
  'DST_MONSTER_DMG',
  'DST_PVP_DMG',
  'DST_MELEE_STEALHP',
  'DST_HEAL',
  'DST_ATKPOWER',
  'DST_ONEHANDMASTER_DMG',
  'DST_TWOHANDMASTER_DMG',
  'DST_YOYOMASTER_DMG',
  'DST_BOWMASTER_DMG',
  'DST_KNUCKLEMASTER_DMG',
  'DST_HAWKEYE_RATE',
  'DST_RESIST_MAGIC_RATE',
  'DST_GIFTBOX',
  'DST_RESTPOINT_RATE',
  'DST_DECREASE_ATK',
  'DST_DECREASE_DEF',
  'DST_DECREASE_ATK_SPEED',
  'DST_IGNORE_DMG_PVP',
  'DST_GOLD',
  'DST_PXP',
  'DST_RESIST_ALL',
  'DST_STAT_ALLUP',
  'DST_HPDMG_UP',
  'DST_DEFHITRATE_DOWN',
  'DST_CURECHR',
  'DST_HP_RECOVERY_RATE',
  'DST_MP_RECOVERY_RATE',
  'DST_FP_RECOVERY_RATE',
  'DST_LOCOMOTION',
  'DST_MASTRY_ALL',
  'DST_ALL_RECOVERY',
  'DST_ALL_RECOVERY_RATE',
  'DST_KILL_ALL',
  'DST_KILL_HP_RATE',
  'DST_KILL_MP_RATE',
  'DST_KILL_FP_RATE',
  'DST_KILL_ALL_RATE',
  'DST_ALL_DEC_RATE'
];

export const itemKind1Options = [
  'IK1_WEAPON', 'IK1_ARMOR', 'IK1_GENERAL', 'IK1_RIDE', 'IK1_SYSTEM',
  'IK1_CHARGED', 'IK1_TREASURE', 'IK1_CONSUMABLE', 'IK1_MATERIAL'
];

export const itemKind2Options = [
  'IK2_WEAPON_DIRECT', 'IK2_WEAPON_MAGIC', 'IK2_ARMOR', 'IK2_ARMORETC',
  'IK2_CLOTH', 'IK2_JEWELRY', 'IK2_FOOD', 'IK2_POTION', 'IK2_BUFF',
  'IK2_QUEST', 'IK2_MATERIAL_GENERAL'
];

export const itemKind3Options = [
  'IK3_AXE', 'IK3_SWD', 'IK3_STICK', 'IK3_STAFF', 'IK3_HELMET',
  'IK3_SUIT', 'IK3_GAUNTLET', 'IK3_BOOTS', 'IK3_SHIELD', 'IK3_CLOAK',
  'IK3_MASK', 'IK3_RING', 'IK3_EARRING', 'IK3_NECKLACE', 'IK3_BRACELET'
];

export const jobOptions = [
  'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST',
  'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER',
  'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER',
  'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER',
  'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER',
  'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER',
  'JOB_ELEMENTOR_MASTER', 'JOB_ALL'
];

export const attackStyleOptions = [
  'AS_HORIZONTAL', 'AS_VERTICAL', 'AS_DIAGONAL', 'AS_THRUST'
];

export const weaponTypeOptions = [
  'WT_MELEE_SWD', 'WT_MELEE_AXE', 'WT_MELEE_STAFF', 'WT_RANGE_BOW', 
  'WT_MAGIC_WAND', 'WT_RANGE_GUN'
];
